### ISSUE TITLE
Show algod error

### ISSUE THREAD

**Issue by 2i2i** [RootSoft/algorand-dart#13]
E.g. in `src/repositories/transaction_repository.dart` -> `sendTransaction` or `sendTransactions` -> `on DioError catch (ex)`:

There is a message from `algod` in `ex.response.data`. Would be helpful to either print this or make it part of the `AlgorandException`.

**Comment by RootSoft** [comment]
You can always get the underlying exception using the included ```cause``` object of ```AlgorandException```.
I might add a new property to include the api error message as well.

```
try {
  ...
} on AlgorandException catch (ex) {
  final cause = ex.cause;
  if (cause is DioError) {
    print(cause.response?.data['message']);
  }
}
```

**Comment by 2i2i** [comment]
You are right. I just could not figure out how to cast the `Object? cause` to a `DioError` (i am new to dart).
I will close the issue.
