### ISSUE TITLE
sendTransactions add waitForConfirmation

### ISSUE THREAD

**Issue by 2i2i** [RootSoft/algorand-dart#15]

**Comment by RootSoft** [comment]
I will add ```waitForConfirmation``` to ```sendTransactions```. 
Note that the method will always and only return the transaction id.

If you are interested in the pending transaction result, you can always do the following:
```
final txId = await algorand.sendTransactions([
  stateTxnSigned,
  paymentSigned,
]);

final result = await algorand.waitForConfirmation(txId);
```

**Comment by RootSoft** [comment]
Added in v1.0.0
