### ISSUE TITLE
Access to asset balances (and other similar)

### ISSUE THREAD

**Issue by 2i2i** [RootSoft/algorand-dart#17]
It seems that access to asset balances is available inside a private variable in `class Algorand`: `late final AccountRepository _accountRepository;`

Should this is exposed or else how to get asset balances (and other account info e.g.)?

**Comment by RootSoft** [comment]
You should use the ```getAccountByAddress()``` method to fetch all account related information.
You can find an example here: https://github.com/RootSoft/algorand-dart/blob/a0e33ecfdfd3a53e1634eb8be0235a244c08e63d/example/assets/assets.dart#L211
