### ISSUE TITLE
opted-in-at-round: null in ApplicationLocalState of opted-in account

### ISSUE THREAD

**Issue by 2i2i** [RootSoft/algorand-dart#22]
This might be an issue or not, or might be an issue else where.

Printing the `ApplicationLocalState` of account 6IMMVVL2ZRXK53KIKA3QNNMC6JGRUR4FXDGHK26UA4IF3C3S4FQOI32WCY on testnet, we get:

```
{id: 32969536, schema: Instance of 'ApplicationStateSchema',
closed-out-at-round: null, deleted: null, key-value: [],
opted-in-at-round: null}
```

Why is the "opted-in-at-round" null? The account is in opted-in, else we would not even have that `ApplicationLocalState`.

**Comment by RootSoft** [comment]
Both Algod and Indexer have an endpoint to get the account information from a given address, however the Algod response does not contain all `ApplicationLocalState` related fields. I think the best bet would always be to check the transaction reference pages:
* Algod: https://developer.algorand.org/docs/rest-apis/algod/v2/#applicationlocalstate
* Indexer: https://developer.algorand.org/docs/rest-apis/indexer/#applicationlocalstate
