### ISSUE TITLE
Incompatable with ipfs due to dio

### ISSUE THREAD

**Issue by 2i2i** [RootSoft/algorand-dart#23]
```
imi:2021-12-01 21:24:44:app_2i2i_shared $ flutter pub add ipfs
Because algorand_dart >=1.0.0 depends on dio ^4.0.1 and every version of ipfs depends on dio ^2.1.16, algorand_dart >=1.0.0 is incompatible with ipfs.
So, because app_2i2i depends on both algorand_dart ^1.0.0 and ipfs any, version solving failed.
pub finished with exit code 65
```

IPFS is quite central to the modern, decentralised world that we are building. It would really be great to be able to use both projects together.

**Comment by 2i2i** [comment]
Although it seems this `ipfs` package does not support `null safety` either. Maybe that package needs updating.

**Comment by RootSoft** [comment]
Yep, that library is outdated and needs to update to support the latest dio version & null safety.
You can write your own wrapper around the IPFS API or use something like Pinata, Temporal Cloud, eternum, ... which have some REST APIs.
