### ISSUE TITLE
How can i call smart contract functions through algorand-dart in flutter

### ISSUE THREAD

**Issue by usama1050** [RootSoft/algorand-dart#24]
i have a smart contract with multiple functions that allow me to pay my bills in crypto currencies .i just want to known how can i use them algorand-dart.

**Comment by RootSoft** [comment]
You can use the SDK just like any other SDK that is available for Algorand.
Take a look here:
https://developer.algorand.org/docs/get-details/dapps/smart-contracts/frontend/apps/

You will be needing `ApplicationCall` transactions in order to call methods on your smart contracts.
