### ISSUE TITLE
assetName, unitName & url restrictions in AssetConfigTransaction

### ISSUE THREAD

**Issue by jasonhtpham** [RootSoft/algorand-dart#27]
I had a lot of trouble creating an asset. And after a whole day with trials and errors, I found out that we had been putting the name of the asset and its unit name incorrectly (longer than permitted?).

We use `AssetConfigTransactionBuilder()` to create the transaction, then sign and send it. We wanted to use this because we need to pass the URL and some notes with the asset creation. So, the weird thing here is:

When I tried with these name:

- **Soccer Dream** (about 12 bytes) => failed.
- **SoccerDream** (about 11 bytes) => failed.
- **soccerdream** (about 11 bytes) => failed.
- **Soccer** (about 6 bytes) => worked.

But when I tried using the assetManager which is simple but does not allow us to specify that many parameters. When I tried to name an asset with **"FlutterCoin"** (about 11 bytes) => it works.

Also, my colleagues passed his URL, which is much longer than 32 bytes, when he uses JavaScript SDK, the transaction always goes through.

However, in the official document of [Algorand](https://developer.algorand.org/docs/get-details/transactions/transactions/#assetname), it says:
![image](https://user-images.githubusercontent.com/61170796/151510233-7ceec38a-3bfc-4617-a54b-964e6949e48d.png)

It would be great if this information could be clarified so other developers will not waste their time.

**Comment by RootSoft** [comment]
Thanks for the feedback @jasonhtpham 
I will improve the documentation in the next release.
`assetManager` and `applicationManager` will also be getting deprecated in favor of using simpler creation methods to construct transactions.

**Comment by jasonhtpham** [comment]
Thank you for replying @RootSoft ! I am looking forward to the new release!
