### ISSUE TITLE
Algoexplorer endpoints will be deprecated

### ISSUE THREAD

**Issue by jffp113** [RootSoft/algorand-dart#28]
The support of the  https://api.algoexplorer.io/v2  and  https://algoexplorerapi.io/v2 will be deprecated and the endpoints will stop working by the end of February 2022.
https://algoexplorer.io/api-dev/v2

&

The support of the  https://api.algoexplorer.io/idx2/v2   and  https://algoexplorerapi.io/idx2/v2  will be deprecated and the endpoints  will stop working by the end of February 2022.
https://algoexplorer.io/api-dev/indexer-v2

The api also will change, some queries to the agorand node are now available only in the indexer: 
`QUERYing for accounts, assets and applications data won't be accepted due to the new nodes on  https://node.algoexplorerapi.io/v2   will only be supporting POSTing TXs to the network, GETting tx parameters and TEAL related calls`

**Comment by RootSoft** [comment]
Thanks for the update!
The endpoints will be reflecting in the next version

**Comment by 2i2i** [comment]
Has this been dealt with already? It might be very important in case the old endpoints stop working.

**Comment by RootSoft** [comment]
The endpoints are updated in v1.0.2.
