### ISSUE TITLE
Error when rekeying address (At least one signature didn't pass verification)

### ISSUE THREAD

**Issue by froze9063** [RootSoft/algorand-dart#31]
Hi all! 

I'm trying to send Rekey transaction by Dart algorand SDK and getting the error when I send raw transaction: `{“message”:“At least one signature didn’t pass verification”}`

My code:
`try{
      final params = await algorand.getSuggestedTransactionParams();
      Address address = Address.fromAlgorandAddress(address: <SENDER>);

      RawTransaction transaction = await (PaymentTransactionBuilder()
        ..sender = address
        ..receiver = address
        ..amount = Algo.toMicroAlgos(0)
        ..rekeyTo = <REKEY_TO_ADDRESS>
        ..suggestedParams = params).build();

      final signedTx = await transaction.sign(<SENDER_OBJECT>!);

      await algorand.sendTransaction(signedTx);

      print("success");
    } on AlgorandException catch (ex) {
      if(ex.cause is DioError){
        print((ex.cause as DioError).response);
      }
      else{
        print((ex).message);
      }
    }`

The issue
![WhatsApp Image 2022-03-07 at 12 21 59](https://user-images.githubusercontent.com/26326325/156977157-413ed567-5fdb-4e5a-aa71-05a594dde207.jpeg)

**Comment by RootSoft** [comment]
Should be fixed in v1.0.2.

**Comment by froze9063** [comment]
Hi I have tested new sdk and it works, than you
