### ISSUE TITLE
Cannot perform AtomicTransfer on ApplicationCreateTransaction

### ISSUE THREAD

**Issue by jasonhtpham** [RootSoft/algorand-dart#33]
I cannot group multiple ApplicationCreateTransaction into an AtomicTransfer. 

I try to convert the ApplicationCreateTransaction back to ApplicationBaseTransaction, but it seems to be impossible to do so. 

Could you please advise me on this?

**Comment by RootSoft** [comment]
@jasonhtpham Can you share some example code that you are trying to do so I can replicate the issue?

**Comment by jasonhtpham** [comment]
I think it was a mistake, but will keep an eye on it. Thanks
