### ISSUE TITLE
Not working on flutter 3.0

### ISSUE THREAD

**Issue by WasimNaryabi** [RootSoft/algorand-dart#35]
Hi, the package not working on flutter 3.0
![image](https://user-images.githubusercontent.com/52564658/171452746-c5a70537-976a-4dee-b034-4eb3fd717cde.png)

**Comment by 1m1-github** [comment]
working for me on flutter 3.0.4

**Comment by RootSoft** [comment]
`algorand_dart` should work on Flutter 3.0.
Make sure to update all dependencies in your `pubspec.yaml` file.
