### ISSUE TITLE
pub.dev version old?

### ISSUE THREAD

**Issue by 2i2i** [RootSoft/algorand-dart#9]
pub.dev latest version (**0.0.2-beta.7**) does not seem to work with the example in 'algorand-dart/example/atomic_transfers/atomic_transfer.dart':

`final algorand = Algorand(algodClient: algodClient);`

fails as constructor has 2 `required` params. Newest code seems to not have `required`.

How can I use the latest version in my flutter project? Do you just need to update the package? Or should I use the latest github branch manually?

thx

**Comment by RootSoft** [comment]
I was still doing some tests with the Algorand constructor. I will publish 0.0.2-beta.8 tomorrow which does not require all arguments in the constructor.

For now (beta.7), you have to provide all clients (Algod, Indexer & KMD).
